package com.ratel.fm.config.database;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

/**
 * 数据库兼容初始化。
 *
 * <p>开发组织：ratel；开发人员：WenZhang；联系方式：18782945613。</p>
 *
 * @author ratel
 */
@Configuration
@ConditionalOnProperty(prefix = "app.database.postgresql-initializer", name = "enabled", havingValue = "true")
public class DatabaseCompatibilityInitializer {

    /**
     * 放宽角色权限集合表上的旧枚举检查约束。
     *
     * <p>实现步骤：
     * 1. 查询 `fm_role_permissions` 表上的 check 约束；
     * 2. 逐个删除旧约束，避免权限枚举新增后历史数据库约束阻止写入；
     * 3. 只处理当前 `fm` 库当前 schema 内的业务表，不操作其他库。</p>
     */
    @Bean
    @Order(0)
    public CommandLineRunner relaxEnumCheckConstraints(JdbcTemplate jdbcTemplate) {
        return args -> {
            // 步骤一：升级历史库时先补齐用户字段、处理重复账号，再创建账号唯一索引，避免旧数据阻止系统启动。
            for (String ddl : userAccountCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }
            for (String ddl : userMenuUsageCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            jdbcTemplate.queryForList("""
                        select conname
                        from pg_constraint c
                        join pg_class t on c.conrelid = t.oid
                        where t.relname = 'fm_role_permissions'
                          and c.contype = 'c'
                        """, String.class)
                    .forEach(name -> jdbcTemplate.execute("alter table fm_role_permissions drop constraint if exists " + name));

            // 步骤四：为历史库中的操作日志表补齐日志管理模块需要的查询展示字段。
            for (String ddl : auditLogCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤五：为历史库补齐基础字典表，保证未经过 Hibernate 自动建表的部署也能启动。
            for (String ddl : basicDictionaryCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤六：为历史库补齐多币种金额快照字段，保存原币金额、币种和当时汇率。
            for (String ddl : currencyCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤七：为历史库补齐统一附件表，其他模块通过业务类型、业务ID和附件ID建立证据文件关系。
            for (String ddl : attachmentCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤八：为物流单补齐行政区划、实际发运日期和操作流水字段，发货地和目的地原字段作为详细地址继续使用。
            for (String ddl : shipmentCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤九：为凭证、采购、库存、应收应付补齐统一业务操作流水表。
            for (String ddl : businessOperationLogCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤十：同步表单校验升级后的字段长度，避免旧库列长度和接口规则不一致。
            for (String ddl : businessFieldLengthCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤十一：为五个核心业务模块补齐项目维度字段，支持按项目筛选、导出和统计。
            for (String ddl : projectDimensionCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤十二：为多公司账套隔离补齐所属公司字段和公司维度唯一索引。
            for (String ddl : companyDimensionCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }

            // 步骤十三：历史 H2 库可能把知识来源建成 ENUM；转成 varchar 后才能兼容新增知识来源类型。
            relaxKnowledgeSourceTypeColumn(jdbcTemplate);

            // 步骤十四：为历史 PostgreSQL 库补齐本地知识库资料表，支持用户上传资料后进入 AI 检索。
            for (String ddl : localKnowledgeCompatibilityDdls()) {
                jdbcTemplate.execute(ddl);
            }
        };
    }

    /**
     * 放宽知识来源类型列。
     *
     * <p>实现步骤：
     * 1. 优先使用 H2 兼容写法把 source_type 改成 varchar；
     * 2. H2 写法失败时使用 PostgreSQL 写法；
     * 3. 如果两种写法都失败则抛出最后一次异常，避免索引来源列仍被旧枚举锁住。</p>
     */
    private void relaxKnowledgeSourceTypeColumn(JdbcTemplate jdbcTemplate) {
        try {
            jdbcTemplate.execute("alter table fm_knowledge_documents alter column source_type varchar(40)");
        } catch (DataAccessException h2StyleFailure) {
            try {
                jdbcTemplate.execute("alter table fm_knowledge_documents alter column source_type type varchar(40)");
            } catch (DataAccessException postgresqlStyleFailure) {
                throw postgresqlStyleFailure;
            }
        }
    }

    /**
     * 本地知识库资料表兼容 DDL。
     *
     * <p>实现步骤：创建本地知识库元数据表，补齐历史库可能缺失的字段和索引，实际正文分片仍写入知识索引或向量库。</p>
     */
    private List<String> localKnowledgeCompatibilityDdls() {
        return List.of(
                """
                create table if not exists fm_local_knowledge_documents (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    title varchar(240) not null,
                    description varchar(500),
                    original_name varchar(300) not null,
                    storage_path varchar(500) not null,
                    suffix varchar(40) not null,
                    content_type varchar(120),
                    file_size bigint not null,
                    status varchar(30) not null,
                    chunk_count integer,
                    ocr_used boolean,
                    organization_code varchar(80) not null,
                    uploaded_by varchar(120),
                    error_message text
                )
                """,
                "alter table fm_local_knowledge_documents add column if not exists title varchar(240)",
                "alter table fm_local_knowledge_documents add column if not exists description varchar(500)",
                "alter table fm_local_knowledge_documents add column if not exists original_name varchar(300)",
                "alter table fm_local_knowledge_documents add column if not exists storage_path varchar(500)",
                "alter table fm_local_knowledge_documents add column if not exists suffix varchar(40)",
                "alter table fm_local_knowledge_documents add column if not exists content_type varchar(120)",
                "alter table fm_local_knowledge_documents add column if not exists file_size bigint",
                "alter table fm_local_knowledge_documents add column if not exists status varchar(30)",
                "alter table fm_local_knowledge_documents add column if not exists chunk_count integer",
                "alter table fm_local_knowledge_documents add column if not exists ocr_used boolean",
                "alter table fm_local_knowledge_documents add column if not exists organization_code varchar(80)",
                "alter table fm_local_knowledge_documents add column if not exists uploaded_by varchar(120)",
                "alter table fm_local_knowledge_documents add column if not exists error_message text",
                "create index if not exists idx_fm_local_knowledge_company on fm_local_knowledge_documents (organization_code)",
                "create index if not exists idx_fm_local_knowledge_status on fm_local_knowledge_documents (status)"
        );
    }

    /**
     * 用户常用菜单兼容 DDL。
     *
     * <p>实现步骤：创建常用菜单统计表并补齐字段，保证旧库升级后首页快捷入口可按用户使用次数排序。</p>
     */
    private List<String> userMenuUsageCompatibilityDdls() {
        return List.of(
                """
                create table if not exists fm_user_menu_usages (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    organization_code varchar(80) not null,
                    user_id bigint not null,
                    username varchar(80) not null,
                    menu_code varchar(120) not null,
                    menu_name varchar(120) not null,
                    route_path varchar(200) not null,
                    use_count bigint not null,
                    last_used_at timestamp(6) with time zone not null
                )
                """,
                "alter table fm_user_menu_usages add column if not exists organization_code varchar(80)",
                "alter table fm_user_menu_usages add column if not exists user_id bigint",
                "alter table fm_user_menu_usages add column if not exists username varchar(80)",
                "alter table fm_user_menu_usages add column if not exists menu_code varchar(120)",
                "alter table fm_user_menu_usages add column if not exists menu_name varchar(120)",
                "alter table fm_user_menu_usages add column if not exists route_path varchar(200)",
                "alter table fm_user_menu_usages add column if not exists use_count bigint",
                "alter table fm_user_menu_usages add column if not exists last_used_at timestamp(6) with time zone",
                "create unique index if not exists uk_fm_user_menu_usage_user_menu on fm_user_menu_usages (organization_code, user_id, menu_code)"
        );
    }

    /**
     * 人员账号兼容 DDL。
     *
     * <p>实现步骤：
     * 1. 补齐头像 Base64 字段；
     * 2. 对历史重复账号按主键追加后缀，保留默认管理员 admin 原值；
     * 3. 创建 username 唯一索引，使账号和身份证号都满足唯一登录要求。</p>
     */
    private List<String> userAccountCompatibilityDdls() {
        return List.of(
                "alter table fm_users add column if not exists avatar_base64 text",
                "alter table fm_users add column if not exists organization_code varchar(80)",
                "update fm_users set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                """
                update fm_users u
                set username = left(u.username, greatest(1, 80 - length('_' || u.id::text))) || '_' || u.id::text
                where u.username = 'admin'
                  and coalesce(u.identity_no, '') <> 'ADMIN_IDENTITY_0001'
                  and exists (
                      select 1
                      from fm_users d
                      where d.identity_no = 'ADMIN_IDENTITY_0001'
                  )
                """,
                """
                update fm_users u
                set username = left(u.username, greatest(1, 80 - length('_' || u.id::text))) || '_' || u.id::text
                where exists (
                    select 1
                    from fm_users x
                    where x.username = u.username
                      and x.id <> u.id
                )
                  and not (u.username = 'admin' and u.identity_no = 'ADMIN_IDENTITY_0001')
                """,
                "alter table fm_users drop constraint if exists uk_fm_users_username",
                "alter table fm_users drop constraint if exists uk_fm_users_identity_no",
                "drop index if exists uk_fm_users_username",
                "drop index if exists uk_fm_users_identity_no",
                "create unique index if not exists uk_fm_users_company_username on fm_users (organization_code, username)",
                "create unique index if not exists uk_fm_users_company_identity on fm_users (organization_code, identity_no) where identity_no is not null"
        );
    }

    /**
     * 操作日志表兼容 DDL。
     *
     * <p>实现步骤：对旧库执行 add column if not exists，新增字段允许为空，避免历史日志无法回填时启动失败。</p>
     */
    private List<String> auditLogCompatibilityDdls() {
        return List.of(
                "alter table fm_user_operation_logs add column if not exists identity_no varchar(40)",
                "alter table fm_user_operation_logs add column if not exists organization_code varchar(80)",
                "update fm_user_operation_logs set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_user_operation_logs add column if not exists operation_module varchar(80)",
                "alter table fm_user_operation_logs add column if not exists operation_function varchar(120)",
                "alter table fm_user_operation_logs add column if not exists success boolean",
                "alter table fm_user_operation_logs add column if not exists response_value varchar(2000)"
        );
    }

    /**
     * 基础字典兼容 DDL。
     *
     * <p>实现步骤：创建基础字典表并补齐字段，后续注释和索引由专用初始化器统一处理。</p>
     */
    private List<String> basicDictionaryCompatibilityDdls() {
        return List.of(
                """
                create table if not exists fm_basic_dictionaries (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    code varchar(80) not null unique,
                    name varchar(120) not null,
                    parent_id bigint,
                    sort_order integer not null,
                    enabled boolean not null,
                    description varchar(2000)
                )
                """,
                "alter table fm_basic_dictionaries add column if not exists created_time timestamp(6) with time zone",
                "alter table fm_basic_dictionaries add column if not exists modify_time timestamp(6) with time zone",
                "alter table fm_basic_dictionaries add column if not exists code varchar(80)",
                "alter table fm_basic_dictionaries add column if not exists name varchar(120)",
                "alter table fm_basic_dictionaries add column if not exists parent_id bigint",
                "alter table fm_basic_dictionaries add column if not exists sort_order integer",
                "alter table fm_basic_dictionaries add column if not exists enabled boolean",
                "alter table fm_basic_dictionaries add column if not exists description varchar(2000)",
                "alter table fm_basic_dictionaries alter column description type varchar(2000)"
        );
    }

    /**
     * 多币种金额字段兼容 DDL。
     *
     * <p>实现步骤：只补齐字段，不强制非空；历史数据会在视图层按人民币和原金额回退，新业务由服务层写入完整快照。</p>
     */
    private List<String> currencyCompatibilityDdls() {
        return List.of(
                "alter table fm_vouchers add column if not exists currency_code varchar(20)",
                "alter table fm_vouchers add column if not exists currency_name varchar(80)",
                "alter table fm_vouchers add column if not exists exchange_rate_to_cny numeric(18, 8)",
                "alter table fm_vouchers add column if not exists total_debit_cny numeric(26, 8)",
                "alter table fm_vouchers add column if not exists total_credit_cny numeric(26, 8)",
                "alter table fm_vouchers add column if not exists belong_month varchar(7)",
                "alter table fm_vouchers add column if not exists source_type varchar(40)",
                "alter table fm_vouchers add column if not exists source_id bigint",
                "alter table fm_vouchers add column if not exists source_title varchar(160)",
                "update fm_vouchers set belong_month = to_char(voucher_date, 'YYYY-MM') where belong_month is null",
                "alter table fm_voucher_lines add column if not exists currency_code varchar(20)",
                "alter table fm_voucher_lines add column if not exists currency_name varchar(80)",
                "alter table fm_voucher_lines add column if not exists exchange_rate_to_cny numeric(18, 8)",
                "alter table fm_voucher_lines add column if not exists debit_amount_cny numeric(26, 8)",
                "alter table fm_voucher_lines add column if not exists credit_amount_cny numeric(26, 8)",
                """
                update fm_voucher_lines line
                set currency_code = coalesce(line.currency_code, voucher.currency_code, 'CNY'),
                    currency_name = coalesce(line.currency_name, voucher.currency_name, '人民币'),
                    exchange_rate_to_cny = coalesce(line.exchange_rate_to_cny, voucher.exchange_rate_to_cny, 1)
                from fm_vouchers voucher
                where line.voucher_id = voucher.id
                  and (line.currency_code is null or line.currency_name is null or line.exchange_rate_to_cny is null)
                """,
                "alter table fm_purchase_orders add column if not exists currency_code varchar(20)",
                "alter table fm_purchase_orders add column if not exists currency_name varchar(80)",
                "alter table fm_purchase_orders add column if not exists exchange_rate_to_cny numeric(18, 8)",
                "alter table fm_purchase_orders add column if not exists total_amount_cny numeric(26, 8)",
                "alter table fm_purchase_orders add column if not exists voucher_id bigint",
                "alter table fm_purchase_orders add column if not exists voucher_no varchar(60)",
                "alter table fm_purchase_order_lines add column if not exists currency_code varchar(20)",
                "alter table fm_purchase_order_lines add column if not exists currency_name varchar(80)",
                "alter table fm_purchase_order_lines add column if not exists exchange_rate_to_cny numeric(18, 8)",
                "alter table fm_purchase_order_lines add column if not exists unit_price_cny numeric(26, 8)",
                "alter table fm_purchase_order_lines add column if not exists amount_cny numeric(26, 8)",
                """
                update fm_purchase_order_lines line
                set currency_code = coalesce(line.currency_code, purchase.currency_code, 'CNY'),
                    currency_name = coalesce(line.currency_name, purchase.currency_name, '人民币'),
                    exchange_rate_to_cny = coalesce(line.exchange_rate_to_cny, purchase.exchange_rate_to_cny, 1)
                from fm_purchase_orders purchase
                where line.purchase_order_id = purchase.id
                  and (line.currency_code is null or line.currency_name is null or line.exchange_rate_to_cny is null)
                """,
                "alter table fm_ar_ap_bills add column if not exists currency_code varchar(20)",
                "alter table fm_ar_ap_bills add column if not exists currency_name varchar(80)",
                "alter table fm_ar_ap_bills add column if not exists exchange_rate_to_cny numeric(18, 8)",
                "alter table fm_ar_ap_bills add column if not exists amount_cny numeric(26, 8)",
                "alter table fm_ar_ap_bills add column if not exists paid_amount_cny numeric(26, 8)",
                "alter table fm_ar_ap_bills add column if not exists voucher_id bigint",
                "alter table fm_ar_ap_bills add column if not exists voucher_no varchar(60)",
                "alter table fm_inventory_ledgers add column if not exists voucher_id bigint",
                "alter table fm_inventory_ledgers add column if not exists voucher_no varchar(60)"
        );
    }

    /**
     * 统一附件表兼容 DDL。
     *
     * <p>实现步骤：先创建附件元数据表，再创建业务附件关系表；已有库重复执行时不会破坏历史数据。</p>
     */
    private List<String> attachmentCompatibilityDdls() {
        return List.of(
                """
                create table if not exists fm_attachments (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    original_name varchar(255) not null,
                    display_name varchar(255) not null,
                    suffix varchar(40),
                    file_size bigint not null,
                    content_type varchar(120),
                    storage_path varchar(500) not null,
                    uploader_id bigint,
                    uploader_username varchar(80)
                )
                """,
                """
                create table if not exists fm_business_attachments (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    business_type varchar(40) not null,
                    business_id bigint not null,
                    attachment_id bigint not null references fm_attachments(id),
                    sort_order integer not null
                )
                """
        );
    }

    /**
     * 物流字段和流水表兼容 DDL。
     *
     * <p>实现步骤：对物流单表补齐发货地/目的地行政区划编码、名称快照和实际发运日期，并创建状态确认流水表。</p>
     */
    private List<String> shipmentCompatibilityDdls() {
        return List.of(
                "alter table fm_shipment_orders add column if not exists origin_division_code varchar(300)",
                "alter table fm_shipment_orders add column if not exists origin_division_name varchar(300)",
                "alter table fm_shipment_orders add column if not exists destination_division_code varchar(300)",
                "alter table fm_shipment_orders add column if not exists destination_division_name varchar(300)",
                "alter table fm_shipment_orders alter column origin_division_code type varchar(300)",
                "alter table fm_shipment_orders alter column origin_division_name type varchar(300)",
                "alter table fm_shipment_orders alter column destination_division_code type varchar(300)",
                "alter table fm_shipment_orders alter column destination_division_name type varchar(300)",
                "alter table fm_shipment_orders alter column related_order_no type varchar(300)",
                "alter table fm_shipment_orders alter column driver_name type varchar(20)",
                "alter table fm_shipment_orders alter column driver_phone type varchar(30)",
                "alter table fm_shipment_orders alter column vehicle_no type varchar(12)",
                "alter table fm_shipment_orders alter column origin type varchar(300)",
                "alter table fm_shipment_orders alter column destination type varchar(300)",
                "alter table fm_shipment_orders alter column remark type varchar(2000)",
                "alter table fm_shipment_orders add column if not exists actual_ship_date date",
                """
                create table if not exists fm_shipment_operation_logs (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    shipment_order_id bigint not null references fm_shipment_orders(id),
                    shipment_no varchar(60) not null,
                    from_status varchar(30),
                    to_status varchar(30) not null,
                    related_order_no varchar(300),
                    document_type varchar(80),
                    transport_mode varchar(80),
                    shipping_organization varchar(120),
                    receiving_organization varchar(120),
                    carrier_name varchar(160) not null,
                    tracking_no varchar(120),
                    driver_name varchar(20),
                    driver_phone varchar(30),
                    vehicle_no varchar(12),
                    origin_division_code varchar(300),
                    origin_division_name varchar(300),
                    destination_division_code varchar(300),
                    destination_division_name varchar(300),
                    origin varchar(300) not null,
                    destination varchar(300) not null,
                    planned_ship_date date not null,
                    actual_ship_date date,
                    delivered_date date,
                    remark varchar(2000),
                    operation_remark varchar(2000),
                    operator_id bigint,
                    operator_username varchar(80),
                    operator_name varchar(120),
                    operation_time timestamp(6) with time zone not null
                )
                """,
                "alter table fm_shipment_operation_logs add column if not exists document_type varchar(80)",
                "alter table fm_shipment_operation_logs add column if not exists transport_mode varchar(80)",
                "alter table fm_shipment_operation_logs add column if not exists shipping_organization varchar(120)",
                "alter table fm_shipment_operation_logs add column if not exists receiving_organization varchar(120)",
                "alter table fm_shipment_operation_logs add column if not exists driver_name varchar(20)",
                "alter table fm_shipment_operation_logs add column if not exists driver_phone varchar(30)",
                "alter table fm_shipment_operation_logs add column if not exists vehicle_no varchar(12)",
                "alter table fm_shipment_operation_logs alter column related_order_no type varchar(300)",
                "alter table fm_shipment_operation_logs alter column origin_division_code type varchar(300)",
                "alter table fm_shipment_operation_logs alter column origin_division_name type varchar(300)",
                "alter table fm_shipment_operation_logs alter column destination_division_code type varchar(300)",
                "alter table fm_shipment_operation_logs alter column destination_division_name type varchar(300)",
                "alter table fm_shipment_operation_logs alter column origin type varchar(300)",
                "alter table fm_shipment_operation_logs alter column destination type varchar(300)",
                "alter table fm_shipment_operation_logs alter column remark type varchar(2000)",
                "alter table fm_shipment_operation_logs alter column operation_remark type varchar(2000)"
        );
    }

    /**
     * 统一业务操作流水兼容 DDL。
     *
     * <p>实现步骤：创建通用业务流水表，支持凭证、采购、库存、应收应付按业务 ID 查询时间轴。</p>
     */
    private List<String> businessOperationLogCompatibilityDdls() {
        return List.of(
                """
                create table if not exists fm_business_operation_logs (
                    id bigint generated by default as identity primary key,
                    created_time timestamp(6) with time zone not null,
                    modify_time timestamp(6) with time zone not null,
                    business_type varchar(40) not null,
                    organization_code varchar(80) not null default 'ORGANIZATION_RATEL',
                    business_id bigint not null,
                    business_no varchar(120) not null,
                    business_title varchar(300) not null,
                    action varchar(60) not null,
                    action_name varchar(120) not null,
                    detail varchar(1000) not null,
                    from_state varchar(120),
                    to_state varchar(120),
                    snapshot varchar(10000),
                    operator_id bigint,
                    operator_username varchar(80),
                    operator_name varchar(120),
                    operation_time timestamp(6) with time zone not null
                )
                """,
                "alter table fm_business_operation_logs add column if not exists organization_code varchar(80)",
                "update fm_business_operation_logs set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'"
        );
    }

    /**
     * 业务表单字段长度兼容 DDL。
     *
     * <p>实现步骤：
     * 1. 人员姓名、联系方式按统一校验规则收紧到 20/30 字符；
     * 2. 摘要、来源单号、备注说明按前后端统一限制调整列长度；
     * 3. 只调整列类型，不修改历史业务数据内容。</p>
     */
    private List<String> businessFieldLengthCompatibilityDdls() {
        return List.of(
                "alter table fm_users alter column real_name type varchar(20)",
                "alter table fm_users alter column phone type varchar(30)",
                "alter table fm_roles alter column description type varchar(2000)",
                "alter table fm_basic_dictionaries alter column description type varchar(2000)",
                "alter table fm_accounting_subjects alter column description type varchar(2000)",
                "alter table fm_vouchers alter column summary type varchar(200)",
                "alter table fm_vouchers alter column source_biz_no type varchar(300)",
                "alter table fm_voucher_lines alter column summary type varchar(200)",
                "alter table fm_purchase_orders alter column source_bill_no type varchar(300)",
                "alter table fm_purchase_orders alter column remark type varchar(2000)",
                "alter table fm_inventory_ledgers alter column related_biz_no type varchar(300)",
                "alter table fm_inventory_ledgers alter column remark type varchar(2000)",
                "alter table fm_ar_ap_bills alter column source_bill_no type varchar(300)",
                "alter table fm_ar_ap_bills alter column payment_plan type varchar(2000)",
                "alter table fm_business_operation_logs alter column snapshot type varchar(10000)"
        );
    }

    /**
     * 项目维度兼容 DDL。
     *
     * <p>实现步骤：
     * 1. 为凭证、采购、物流、库存和应收应付主表补齐项目编码与项目名称快照；
     * 2. 为物流状态确认流水补齐项目快照，保证查看流水能展示确认时所属项目；
     * 3. 新字段允许为空，兼容升级前历史业务数据。</p>
     */
    private List<String> projectDimensionCompatibilityDdls() {
        return List.of(
                "alter table fm_vouchers add column if not exists project_code varchar(80)",
                "alter table fm_vouchers add column if not exists project_name varchar(160)",
                "alter table fm_purchase_orders add column if not exists project_code varchar(80)",
                "alter table fm_purchase_orders add column if not exists project_name varchar(160)",
                "alter table fm_shipment_orders add column if not exists project_code varchar(80)",
                "alter table fm_shipment_orders add column if not exists project_name varchar(160)",
                "alter table fm_shipment_operation_logs add column if not exists project_code varchar(80)",
                "alter table fm_shipment_operation_logs add column if not exists project_name varchar(160)",
                "alter table fm_inventory_ledgers add column if not exists project_code varchar(80)",
                "alter table fm_inventory_ledgers add column if not exists project_name varchar(160)",
                "alter table fm_ar_ap_bills add column if not exists project_code varchar(80)",
                "alter table fm_ar_ap_bills add column if not exists project_name varchar(160)",
                "alter table fm_workflow_instances add column if not exists project_code varchar(80)",
                "alter table fm_workflow_instances add column if not exists project_name varchar(160)"
        );
    }

    /**
     * 所属公司账套隔离兼容 DDL。
     *
     * <p>实现步骤：
     * 1. 为用户会话、科目、凭证、采购、物流、库存、应收应付、操作流水补齐 organization_code；
     * 2. 将历史空值回填到系统默认所属公司；
     * 3. 删除历史全局唯一约束，改为所属公司内唯一；
     * 4. 创建公司维度查询索引，保证列表、统计和 AI 检索不会跨账套扫描。</p>
     */
    private List<String> companyDimensionCompatibilityDdls() {
        return List.of(
                "alter table fm_user_login_sessions add column if not exists organization_code varchar(80)",
                "update fm_user_login_sessions set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_accounting_subjects add column if not exists organization_code varchar(80)",
                "update fm_accounting_subjects set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_vouchers add column if not exists organization_code varchar(80)",
                "update fm_vouchers set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_purchase_orders add column if not exists organization_code varchar(80)",
                "update fm_purchase_orders set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_shipment_orders add column if not exists organization_code varchar(80)",
                "update fm_shipment_orders set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_inventory_ledgers add column if not exists organization_code varchar(80)",
                "update fm_inventory_ledgers set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_ar_ap_bills add column if not exists organization_code varchar(80)",
                "update fm_ar_ap_bills set organization_code = 'ORGANIZATION_RATEL' where organization_code is null or organization_code = '' or organization_code = 'ratel'",
                "alter table fm_knowledge_documents add column if not exists organization_code varchar(80)",
                "alter table fm_vouchers drop constraint if exists uk_fm_vouchers_voucher_no",
                "alter table fm_purchase_orders drop constraint if exists uk_fm_purchase_orders_order_no",
                "alter table fm_shipment_orders drop constraint if exists uk_fm_shipment_orders_shipment_no",
                "alter table fm_inventory_ledgers drop constraint if exists uk_fm_inventory_ledgers_movement_no",
                "alter table fm_ar_ap_bills drop constraint if exists uk_fm_ar_ap_bills_bill_no",
                "alter table fm_accounting_subjects drop constraint if exists uk_fm_accounting_subjects_code",
                "drop index if exists uk_fm_vouchers_voucher_no",
                "drop index if exists uk_fm_purchase_orders_order_no",
                "drop index if exists uk_fm_shipment_orders_shipment_no",
                "drop index if exists uk_fm_inventory_ledgers_movement_no",
                "drop index if exists uk_fm_ar_ap_bills_bill_no",
                "drop index if exists uk_fm_accounting_subjects_code",
                "create unique index if not exists uk_fm_subjects_company_code on fm_accounting_subjects (organization_code, code)",
                "create unique index if not exists uk_fm_vouchers_company_no on fm_vouchers (organization_code, voucher_no)",
                "create unique index if not exists uk_fm_purchase_company_no on fm_purchase_orders (organization_code, order_no)",
                "create unique index if not exists uk_fm_shipment_company_no on fm_shipment_orders (organization_code, shipment_no)",
                "create unique index if not exists uk_fm_inventory_company_no on fm_inventory_ledgers (organization_code, movement_no)",
                "create unique index if not exists uk_fm_ar_ap_company_no on fm_ar_ap_bills (organization_code, bill_no)"
        );
    }
}
